packages:
  - apps/*
  - packages/shared/*
  - packages/features/*
  - packages/compositions/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.87.1
  "@trpc/client": ^11.5.1
  "@trpc/server": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
  eslint: ^9.35.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  zod: ^4.1.5
  "@upstash/redis": ^1.34.3
  "@upstash/ratelimit": ^2.0.5
  "yahoo-finance2": ^2.13.3

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

nodeLinker: hoisted
linkWorkspacePackages: true
